In [88]:
import pandas as pd
from multiprocessing import Pool

folder_dir  = r"/Users/anora/Library/CloudStorage/Dropbox-TeamMG/Wanru Wu/Cloudseeding_Anora/抗议数据/te"

df1 = pd.read_stata("/Users/anora/Library/CloudStorage/Dropbox-TeamMG/Wanru Wu/Cloudseeding_Anora/抗议数据/final_panel_newweibo.dta")
df2 = pd.read_stata("/Users/anora/Library/CloudStorage/Dropbox-TeamMG/Wanru Wu/Cloudseeding_Anora/抗议数据/final/final_panel_newweibo.dta")

In [90]:
df1 = df1.sort_values(by=['adcode','date']).reset_index(drop=True)
df2 = df2.sort_values(by=['adcode','date']).reset_index(drop=True)

In [89]:
df2

,adcode,date,rainfall,n_cloudseeding,n_prt_rfa,size_rfa,size_original_rfa,n_prt_weibo,size_weibo,size_original_weibo,city,citycode,week
0,110000,2010-01-01,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,1100,1.0
1,110000,2010-01-02,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,1100,1.0
2,110000,2010-01-03,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,1100,1.0
3,110000,2010-01-04,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,1100,1.0
4,110000,2010-01-05,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,1100,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17417736,659010,2024-12-27,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,659010,783.0
17417737,659010,2024-12-28,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,659010,783.0
17417738,659010,2024-12-29,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,659010,783.0
17417739,659010,2024-12-30,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,659010,783.0
17417740,659010,2024-12-31,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,659010,783.0

In [91]:
from pandas.testing import assert_frame_equal

df1.equals(df2)

True

In [54]:
# Returns only the rows/columns that differ
diff = df1.compare(df2)
print(diff)

      county       month        day                 event_id  \
        self other  self other self other               self
34       NaN   NaN   NaN   NaN  NaN   NaN  341222_2011-08-07
35       NaN   NaN   NaN   NaN  NaN   NaN  110000_2011-08-06
37       NaN   NaN   NaN   NaN  NaN   NaN  110000_2011-08-12
38       NaN   NaN   NaN   NaN  NaN   NaN  110000_2011-08-13
39       NaN   NaN   NaN   NaN  NaN   NaN  110000_2013-06-28
...      ...   ...   ...   ...  ...   ...                ...
35138    NaN   NaN   NaN   NaN  NaN   NaN  511902_2014-08-06
35190    NaN   NaN   NaN   NaN  NaN   NaN  654201_2014-03-24
35191    NaN   NaN   NaN   NaN  NaN   NaN  654201_2014-03-22
35192    NaN   NaN   NaN   NaN  NaN   NaN  654201_2014-03-25
35193    NaN   NaN   NaN   NaN  NaN   NaN  654201_2014-03-20

                            size_max             size_original
                   other        self       other          self       other
34     110000_2011-08-06    2.430762    7.804805      2.430762    7.804805
35     341222_2011-08-07    7.804805    2.430762      7.804805    2.430762
37     130684_2011-08-20   18.343559    0.000000     18.343559         NaN
38     110000_2013-06-28   15.352833    0.000000     15.352833         NaN
39     110000_2011-08-13    0.000000   15.352833           NaN   15.352833
...                  ...         ...         ...           ...         ...
35138  511902_2014-01-22   20.693214   51.902420     20.693214   51.902420
35190  654201_2014-03-20   85.830673  192.498978     85.830673  192.498978
35191  654201_2014-03-24   46.366127   85.830673     46.366127   85.830673
35192  654201_2014-03-22   96.522873   46.366127     96.522873   46.366127
35193  654201_2014-03-25  192.498978   96.522873    192.498978   96.522873

[5434 rows x 12 columns]

In [6]:
df1= df.loc[(df['year1'].isna()) | (df['month1'].isna()) | (df['day1'].isna())]
df1['time1'] = df1['time1'].astype(str)
df1['time1'] = df1['time1'].str.replace("[", "")
df1['time1'] = df1['time1'].str.replace("]", "")
df1['time1'] = df1['time1'].str.replace("，", ",")
df1['time1'] = df1['time1'].str.replace("、", ",")
df1['time1'] = df1['time1'].str.replace("；", ",")
df1['time1'] = df1['time1'].str.replace(";", ",")
df1['time1'] = df1['time1'].str.split(',')
df1

/var/folders/2c/w1hx20mn0q59vvy9k05lgrl00000gn/T/ipykernel_33239/2298133595.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['time1'] = df1['time1'].astype(str)
/var/folders/2c/w1hx20mn0q59vvy9k05lgrl00000gn/T/ipykernel_33239/2298133595.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['time1'] = df1['time1'].str.replace("[", "")
/var/folders/2c/w1hx20mn0q59vvy9k05lgrl00000gn/T/ipykernel_33239/2298133595.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['time1'] = df1['time1'].str.replace("]", "")
/var/folders/2c/w1hx20mn0q59vvy9k05lgrl00000gn/T/ipykernel_33239/2298133595.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['time1'] = df1['time1'].str.replace("，", ",")
/var/folders/2c/w1hx20mn0q59vvy9k05lgrl00000gn/T/ipykernel_33239/2298133595.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['time1'] = df1['time1'].str.replace("、", ",")
/var/folders/2c/w1hx20mn0q59vvy9k05lgrl00000gn/T/ipykernel_33239/2298133595.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['time1'] = df1['time1'].str.replace("；", ",")
/var/folders/2c/w1hx20mn0q59vvy9k05lgrl00000gn/T/ipykernel_33239/2298133595.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['time1'] = df1['time1'].str.replace(";", ",")
/var/folders/2c/w1hx20mn0q59vvy9k05lgrl00000gn/T/ipykernel_33239/2298133595.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['time1'] = df1['time1'].str.split(',')

,posts,size_mean,省,市,区,adcode,year,month,day,citycode,time1,time2,month1,year1,day1
0,@头条新闻湖北省孝感市汉川新河达利园后面一房子我们跟他做的他不给钱，户主为，李官庭，王小桃，...,NaN,湖北省,<NA>,汉川市,420984,2014,6,19,2014-06,"[2012年3月, 2011年底, 2013年4月]",nan,NaN,NaN,NaN
1,"""""""""""""""2014年5月12日晚上，云南省昭通市昭阳区紫光酒店对面发生暴打事件，据说是农...",NaN,云南省,<NA>,昭阳区,530602,2013,3,1,2013-03,[2014年5月12日晚上],nan,NaN,NaN,NaN
6,2013年3月21日广西来宾武宣县政府强征土荫塘村田地及房屋，村民拒绝强征。强拆，被强行抓捕...,18.248148,广西壮族自治区,<NA>,武宣县,451323,2013,3,25,2013-03,[2013年3月21日],nan,NaN,NaN,NaN
7,【处置违规拆迁纠纷】2016年9月22日，渭南韩城桑树坪所根据报警迅速赶赴辖区街道创卫拆迁现...,6.124828,陕西省,<NA>,韩城市,610581,2016,9,22,2016-09,[2016年9月22日],nan,NaN,NaN,NaN
8,@柳记七啊九月二十五日凌晨四五点，石狮市锦尚镇港前村的临时灵堂再次被政府强拆，先祖骸骨无处置...,31.584674,福建省,<NA>,石狮市,350581,2014,10,9,2014-10,[九月二十五日凌晨四五点],nan,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43540,@京V舆情 //山西金恒公司200多职工因不同意公司强迫买断工龄的做法。从2017年2月被公...,NaN,山西省,<NA>,<NA>,140700,2017,7,21,2017-07,[2017年2月],nan,NaN,NaN,NaN
43541,爆料 河南省开封市土城四组的村民，近几年来村民来一直生活在惶恐不安的生活中。夷山大厦以及...,NaN,河南省,<NA>,<NA>,410200,2017,4,27,2017-04,"[2008年, 2014年, 2015年]",None,NaN,NaN,NaN
43542,爆料 河南省开封市土城四组的村民，近几年来村民来一直生活在惶恐不安的生活中。夷山大厦以及...,NaN,河南省,<NA>,<NA>,410200,2017,4,27,2017-04,"[2008年, 2014年, 2015年]",None,NaN,NaN,NaN
43543,爆料 河南省开封市土城四组的村民，近几年来村民来一直生活在惶恐不安的生活中。夷山大厦以及...,NaN,河南省,<NA>,<NA>,410200,2017,4,27,2017-04,"[2008年, 2014年, 2015年]",None,NaN,NaN,NaN
43545,云南昆明世纪城业主维权被捏造“寻衅滋事”假象，刑拘9名业主的事件，望领导及时对冤案给予昭雪纠...,0.853011,云南省,<NA>,<NA>,530100,2019,6,27,2019-06,"[事件一：云南昆明世纪城业主维权被捏造“寻衅滋事”假象, 刑拘9名业主的事件在未具体指明日期...",nan,NaN,NaN,NaN

In [3]:
df['time2'] = df['time2'].str.replace("、", ",")
df['time2'] = df['time2'].str.replace("；", ",")
df

,posts,size_mean,省,市,区,adcode,year,month,day,citycode,time1,time2
0,@头条新闻湖北省孝感市汉川新河达利园后面一房子我们跟他做的他不给钱，户主为，李官庭，王小桃，...,NaN,湖北省,<NA>,汉川市,420984,2014,6,19,2014-06,2012年3月；2011年底；2013年4月,nan
1,"""""""""""""""2014年5月12日晚上，云南省昭通市昭阳区紫光酒店对面发生暴打事件，据说是农...",NaN,云南省,<NA>,昭阳区,530602,2013,3,1,2013-03,2014年5月12日晚上,nan
2,河南上蔡县为招商引资强征耕地近五百亩。3月20日上午，河南省上蔡县蔡都镇景庄村，绿油油的麦田...,2.520859,河南省,<NA>,上蔡县,411722,2012,3,26,2012-03,3月20日上午,2012年3月20日上午
3,山东临清强卖土地逼死老农山东省临清市金郝庄乡政府副乡长，管理区书记逼死老实农民张胜昌，201...,NaN,山东省,<NA>,临清市,371581,2013,2,26,2013-02,2013年2月21日,2013年2月21日
4,2月9日上午十点左右，本网记者出差路过新乡，在京港澳高速新乡东站，出站口被新乡县七里营镇八柳...,9.037017,河南省,<NA>,新乡县,410721,2015,2,26,2015-02,2月9日上午十点左右,2015年2月9日
...,...,...,...,...,...,...,...,...,...,...,...,...
34344,爆料 河南省开封市土城四组的村民，近几年来村民来一直生活在惶恐不安的生活中。夷山大厦以及...,NaN,河南省,<NA>,<NA>,410200,2017,4,27,2017-04,2008年、2014年、2015年,"None, None, None"
34345,2016年年底，吉林市联通开始裁员，某部门裁员比例近半，被裁的百人聚集在市政府门口。突然想起...,45.534698,吉林省,<NA>,<NA>,220200,2017,1,3,2017-01,2016年年底,2016年12月31日
34346,云南昆明世纪城业主维权被捏造“寻衅滋事”假象，刑拘9名业主的事件，望领导及时对冤案给予昭雪纠...,0.853011,云南省,<NA>,<NA>,530100,2019,6,27,2019-06,事件一：云南昆明世纪城业主维权被捏造“寻衅滋事”假象，刑拘9名业主的事件在未具体指明日期的情...,nan
34347,周五了，要罢工罢工 2南京·南京钟山,2.729843,江苏省,<NA>,<NA>,320100,2017,7,7,2017-07,"周五, 下午",2017年7月8日
34348,医生们正在罢工请愿、人一定要想清三个问题……院外，第三你能放弃什么！院长黑着脸一言不发……院...,18.233764,浙江省,<NA>,<NA>,330200,2017,8,14,2017-08,2017年8月14日,2017年8月14日