In [69]:
import xarray as xr
import os
import geopandas as gpd
import xarray as xr
import geopandas as gpd
import pandas as pd
import juliandate as jd
from multiprocessing import Pool

In [70]:
 # load all files
os.chdir("/Users/anora/Team MG Dropbox/Wanru Wu/Cloudseeding_Anora/SSF/raw/terra")
path = os.getcwd() 

# Get the list of all files and directories 
all_files = os.listdir(path) 
data_files_terra = [file for file in all_files if file.find("CERES_SSF_Terra-XTRK_Edition4A")!=-1]

In [71]:
# Load the county-level district file
county_gdf = gpd.read_file(os.path.dirname(os.getcwd()) + "/district/district.shp")
county_gdf = county_gdf.to_crs("EPSG:4326")

In [72]:
with xr.open_dataset(data_files_terra[1]) as ds:
    ds

In [ ]:
ds

<xarray.Dataset>
Dimensions:                                                        (
                                                                    time: 3763258,
                                                                    The_8_most_prevalent_surface_types: 8,
                                                                    Conditions_clear__lower__upper__upper_over_lower: 4,
                                                                    Lower_and_Upper_Cloud_Layers: 2)
Coordinates:
  * time                                                           (time) datetime64[ns] ...
Dimensions without coordinates: The_8_most_prevalent_surface_types,
                                Conditions_clear__lower__upper__upper_over_lower,
                                Lower_and_Upper_Cloud_Layers
Data variables: (12/86)
    lon                                                            (time) float32 ...
    lat                                                            (time) float32 ...
    Time_of_observation                                            (time) float64 ...
    Longitude_of_CERES_FOV_at_surface                              (time) float32 ...
    Colatitude_of_CERES_FOV_at_surface                             (time) float32 ...
    Longitude_of_subsatellite_point_at_surface_at_observation      (time) float32 ...
    ...                                                             ...
    Percentage_of_CERES_FOV_with_MODIS_deep_blue_aerosol           (time) float32 ...
    PSF_wtd_MOD04_deep_blue_aerosol_optical_depth_land__0_550_     (time) float32 ...
    PSF_wtd_MOD04_deep_blue_angstrom_exponent_land                 (time) float32 ...
    PSF_wtd_MOD04_deep_blue_single_scattering_albedo_land__0_470_  (time) float32 ...
    Packet_number                                                  (time) float32 ...
    Scan_sample_number                                             (time) float32 ...
Attributes:
    Conventions:                CF-1.0
    Subsetter_title:            ASDC CERES Subset
    Subsetter_version:          2.9.b1
    Subsetter_institution:      Atmospheric Science Data Center (ASDC) http:/...
    Subsetter_history:          2025-05-31T21:12:07 -0400 SubsetCeresSsf
    Subsetter_temporalFilter:   2011-01-01T00:00:00.000000Z to 2011-12-31T23:...
    Subsetter_spatialFilter:    POLYGON ((73 18, 73 54, 135 54, 135 18, 73 18))
    Subsetter_parameterFilter:  none
    platform:                   Terra
    history_json:               [{"$schema": "https://harmony.earthdata.nasa....

In [74]:
districts = county_gdf

lons = ds["lon"].values
lats = ds["lat"].values

# Create GeoDataFrame of points
point_gdf = gpd.GeoDataFrame(
    geometry=gpd.points_from_xy(lons, lats),
    crs="EPSG:4326"
)

# Spatial join - extract county code
joined = gpd.sjoin(point_gdf, districts, how="left", predicate="within")

# Extract date
dates = pd.to_datetime(ds["time"].values).tz_localize("UTC").tz_convert("Asia/Shanghai").tz_localize(None).values.astype("datetime64[D]").astype("U10")
ds["date"] = xr.DataArray(dates, dims="time")

# Add back to the netcdf
ds["region"] = xr.DataArray(joined["dt_adcode"].to_numpy(), dims="time")
print("added region and time variable")

# Filter valid rows
cat1 = pd.Categorical(ds["region"].values)
mask = (cat1.codes >= 0) 
ds_masked = ds.isel(time=mask)  
print("masked")

# Created combined group of region and time
region_vals = ds_masked["region"].values
date_vals = ds_masked["date"].values
combined_labels = [f"{r}_{d}" for r, d in zip(region_vals, date_vals)]
ds_masked["combined_group"] = xr.DataArray(combined_labels, dims=["time"])
print("assigned combined group")

added region and time variable
masked
assigned combined group

In [80]:
# Select variables to keep
variables_to_keep = ['CERES_SW_TOA_flux___upwards',
                     'CERES_solar_zenith_at_surface',
                     'date',
                     'region']
ds_selected = ds_masked[variables_to_keep]
print("selected target variables")

# Convert to dataframe
df_temp = ds_selected.to_dataframe()
print("converted")

selected target variables
converted

In [82]:
max(df_temp.CERES_solar_zenith_at_surface)

143.2674102783203

In [87]:
test3 = df_temp[df_temp['CERES_solar_zenith_at_surface']>90]
test3.head(500)

,CERES_SW_TOA_flux___upwards,CERES_solar_zenith_at_surface,date,region
time,,,,
2011-07-02 12:37:56.923075328,0.0,103.714172,2011-07-02,220623
2011-07-02 12:37:56.963067136,0.0,103.269844,2011-07-02,220582
2011-07-02 12:37:58.523066624,0.0,103.222809,2011-07-02,220582
2011-07-02 12:37:58.563098624,0.0,103.653923,2011-07-02,220681
2011-07-02 12:38:03.453074176,0.0,103.929924,2011-07-02,222405
2011-07-02 12:38:03.473070080,0.0,103.780579,2011-07-02,222406
2011-07-02 12:38:03.493065728,0.0,103.617249,2011-07-02,222406
2011-07-02 12:38:03.513061632,0.0,103.439713,2011-07-02,220621
2011-07-02 12:38:03.533057536,0.0,103.243523,2011-07-02,220681
2011-07-02 12:38:03.543075584,0.0,103.135780,2011-07-02,220681
2011-07-02 12:38:03.553053440,0.0,103.022568,2011-07-02,220521
2011-07-02 12:38:03.563071488,0.0,102.902237,2011-07-02,220582
2011-07-02 12:38:05.123070976,0.0,102.855087,2011-07-02,220502
2011-07-02 12:38:05.133048832,0.0,102.971771,2011-07-02,220602
2011-07-02 12:38:05.143066880,0.0,103.082535,2011-07-02,220681
2011-07-02 12:38:05.153084928,0.0,103.187027,2011-07-02,220681
2011-07-02 12:38:05.173080832,0.0,103.377419,2011-07-02,220621
2011-07-02 12:38:05.193076736,0.0,103.551933,2011-07-02,222426
2011-07-02 12:38:05.213072640,0.0,103.707596,2011-07-02,222406
2011-07-02 12:38:05.233068544,0.0,103.852646,2011-07-02,222405
2011-07-02 12:38:05.273060096,0.0,104.111519,2011-07-02,222404
2011-07-02 12:38:05.293056000,0.0,104.226982,2011-07-02,222404
2011-07-02 12:38:09.983032576,0.0,103.998558,2011-07-02,222404
2011-07-02 12:38:10.003068672,0.0,103.883003,2011-07-02,222404
2011-07-02 12:38:10.023064576,0.0,103.759521,2011-07-02,222404
2011-07-02 12:38:10.043060480,0.0,103.627563,2011-07-02,222402
2011-07-02 12:38:10.063056384,0.0,103.485237,2011-07-02,222405
2011-07-02 12:38:10.083052288,0.0,103.329460,2011-07-02,222426
2011-07-02 12:38:10.103048192,0.0,103.159233,2011-07-02,220621
2011-07-02 12:38:10.123043840,0.0,102.975166,2011-07-02,220621
2011-07-02 12:38:10.143039744,0.0,102.766342,2011-07-02,220605
2011-07-02 12:38:10.153057792,0.0,102.653595,2011-07-02,220521
2011-07-02 12:38:10.163035648,0.0,102.534706,2011-07-02,220524
2011-07-02 12:38:11.723035392,0.0,102.486816,2011-07-02,220524
2011-07-02 12:38:11.733053440,0.0,102.602982,2011-07-02,220524
2011-07-02 12:38:11.743031040,0.0,102.714134,2011-07-02,220622
2011-07-02 12:38:11.763067136,0.0,102.913330,2011-07-02,220621
2011-07-02 12:38:11.783063040,0.0,103.095894,2011-07-02,222426
2011-07-02 12:38:11.803058944,0.0,103.259537,2011-07-02,222406
2011-07-02 12:38:11.823054848,0.0,103.408783,2011-07-02,222405
2011-07-02 12:38:11.843050752,0.0,103.548126,2011-07-02,222402
2011-07-02 12:38:11.863046656,0.0,103.676643,2011-07-02,222402
2011-07-02 12:38:11.883042560,0.0,103.796295,2011-07-02,222424
2011-07-02 12:38:11.903038208,0.0,103.908203,2011-07-02,222404
2011-07-02 12:38:16.573019136,0.0,103.679581,2011-07-02,231086
2011-07-02 12:38:16.593014784,0.0,103.568657,2011-07-02,222424
2011-07-02 12:38:16.613010688,0.0,103.449684,2011-07-02,222424
2011-07-02 12:38:16.633046784,0.0,103.322472,2011-07-02,222424
2011-07-02 12:38:16.653042688,0.0,103.185417,2011-07-02,222401
2011-07-02 12:38:16.673038592,0.0,103.037239,2011-07-02,222426
2011-07-02 12:38:16.693034496,0.0,102.875221,2011-07-02,222403
2011-07-02 12:38:16.713030400,0.0,102.699142,2011-07-02,220282
2011-07-02 12:38:16.733026304,0.0,102.504608,2011-07-02,220622
2011-07-02 12:38:16.743044352,0.0,102.397797,2011-07-02,220523
2011-07-02 12:38:16.753021952,0.0,102.285583,2011-07-02,220524
2011-07-02 12:38:16.763040000,0.0,102.167267,2011-07-02,220581
2011-07-02 12:38:18.323039744,0.0,102.118568,2011-07-02,220581
2011-07-02 12:38:18.333017600,0.0,102.234207,2011-07-02,220524
2011-07-02 12:38:18.343035648,0.0,102.344864,2011-07-02,220523
2011-07-02 12:38:18.353013504,0.0,102.446732,2011-07-02,220282
2011-07-02 12:38:18.373009152,0.0,102.636345,2011-07-02,220282
2011-07-02 12:38:18.393045248,0.0,102.809418,2011-07-02,222403
2011-07-02 12:38:18.413041152,0.0,102.963814,2011-07-02,222426
2011-07-02 12:38:18.433037056,0.0,103.107727,2011-07-02,222401
2011-07-02 12:38:18.453032960,0.0,103.241119,2011-07-02,222424
2011-07-02 12:38:18.473028864,0.0,103.364632,2011-07-02,222424
2011-07-02 12:38:18.493024768,0.0,103.479240,2011-07-02,231086
2011-07-02 12:38:18.513020672,0.0,103.587791,2011-07-02,231086
2011-07-02 12:38:23.163005440,0.0,103.358810,2011-07-02,231086
2011-07-02 12:38:23.183001344,0.0,103.250580,2011-07-02,231086
2011-07-02 12:38:23.202997248,0.0,103.135902,2011-07-02,222424
2011-07-02 12:38:23.222992896,0.0,103.013367,2011-07-02,222424
2011-07-02 12:38:23.243028992,0.0,102.882446,2011-07-02,222424
2011-07-02 12:38:23.263024896,0.0,102.741280,2011-07-02,222403
2011-07-02 12:38:23.283020800,0.0,102.586845,2011-07-02,222403
2011-07-02 12:38:23.303016704,0.0,102.418015,2011-07-02,220282
2011-07-02 12:38:23.323012608,0.0,102.235565,2011-07-02,220282
2011-07-02 12:38:23.343008512,0.0,102.028603,2011-07-02,220284
2011-07-02 12:38:23.353026560,0.0,101.916885,2011-07-02,220421
2011-07-02 12:38:23.363004416,0.0,101.799110,2011-07-02,220421
2011-07-02 12:38:24.923003904,0.0,101.750046,2011-07-02,220422
2011-07-02 12:38:24.933021952,0.0,101.865166,2011-07-02,220581
2011-07-02 12:38:24.942999808,0.0,101.975349,2011-07-02,220284
2011-07-02 12:38:24.962995712,0.0,102.172813,2011-07-02,220282
2011-07-02 12:38:24.983031808,0.0,102.353859,2011-07-02,220281
2011-07-02 12:38:25.003027712,0.0,102.516159,2011-07-02,222403
2011-07-02 12:38:25.023023360,0.0,102.664215,2011-07-02,222403
2011-07-02 12:38:25.043019264,0.0,102.802483,2011-07-02,222424
2011-07-02 12:38:25.063015168,0.0,102.930016,2011-07-02,231084
2011-07-02 12:38:25.083011072,0.0,103.048790,2011-07-02,231085
2011-07-02 12:38:25.103006976,0.0,103.159882,2011-07-02,231086
2011-07-02 12:38:25.123002880,0.0,103.263771,2011-07-02,231086
2011-07-02 12:38:29.752991744,0.0,103.036125,2011-07-02,231086
2011-07-02 12:38:29.772987648,0.0,102.930878,2011-07-02,231086
2011-07-02 12:38:29.792983552,0.0,102.820740,2011-07-02,231085
2011-07-02 12:38:29.812979456,0.0,102.702621,2011-07-02,231084
2011-07-02 12:38:29.832975360,0.0,102.576355,2011-07-02,231084
2011-07-02 12:38:29.853011456,0.0,102.440323,2011-07-02,231084
2011-07-02 12:38:29.873007360,0.0,102.293297,2011-07-02,222403
2011-07-02 12:38:29.893003008,0.0,102.132568,2011-07-02,220281
2011-07-02 12:38:29.912998912,0.0,101.957932,2011-07-02,220281
2011-07-02 12:38:29.932994816,0.0,101.765038,2011-07-02,220284
2011-07-02 12:38:29.942972672,0.0,101.659142,2011-07-02,220284
2011-07-02 12:38:29.952990720,0.0,101.547913,2011-07-02,220323
2011-07-02 12:38:29.963008768,0.0,101.430656,2011-07-02,220422
2011-07-02 12:38:31.523008256,0.0,101.381348,2011-07-02,220422
2011-07-02 12:38:31.532986112,0.0,101.495956,2011-07-02,220323
2011-07-02 12:38:31.543004160,0.0,101.605659,2011-07-02,220112
2011-07-02 12:38:31.552982016,0.0,101.707489,2011-07-02,220221
2011-07-02 12:38:31.572977920,0.0,101.894661,2011-07-02,220281
2011-07-02 12:38:31.592973824,0.0,102.066315,2011-07-02,220281
2011-07-02 12:38:31.613009920,0.0,102.219475,2011-07-02,222403
2011-07-02 12:38:31.633005824,0.0,102.362274,2011-07-02,231084
2011-07-02 12:38:31.653001728,0.0,102.494644,2011-07-02,231084
2011-07-02 12:38:31.672997376,0.0,102.617249,2011-07-02,231002
2011-07-02 12:38:31.692993280,0.0,102.731018,2011-07-02,231085
2011-07-02 12:38:31.712989184,0.0,102.838242,2011-07-02,231086
2011-07-02 12:38:31.732985088,0.0,102.938713,2011-07-02,231085
2011-07-02 12:38:31.853000448,0.0,103.445030,2011-07-02,230382
2011-07-02 12:38:36.222962688,0.0,103.219864,2011-07-02,230382
2011-07-02 12:38:36.242958592,0.0,103.144341,2011-07-02,230382
2011-07-02 12:38:36.262954496,0.0,103.065300,2011-07-02,230382
2011-07-02 12:38:36.322982400,0.0,102.805099,2011-07-02,230321
2011-07-02 12:38:36.342978304,0.0,102.709900,2011-07-02,230321
2011-07-02 12:38:36.362973952,0.0,102.609909,2011-07-02,231085
2011-07-02 12:38:36.382969856,0.0,102.501869,2011-07-02,231085
2011-07-02 12:38:36.402965760,0.0,102.388596,2011-07-02,231003
2011-07-02 12:38:36.422961664,0.0,102.266327,2011-07-02,231083
2011-07-02 12:38:36.442957568,0.0,102.137039,2011-07-02,231083
2011-07-02 12:38:36.462993664,0.0,101.996246,2011-07-02,222403
2011-07-02 12:38:36.482989568,0.0,101.843697,2011-07-02,230184
2011-07-02 12:38:36.502985472,0.0,101.675507,2011-07-02,220281
2011-07-02 12:38:36.522981120,0.0,101.493706,2011-07-02,220204
2011-07-02 12:38:36.542977024,0.0,101.289307,2011-07-02,220112
2011-07-02 12:38:36.552954880,0.0,101.178551,2011-07-02,220104
2011-07-02 12:38:36.562972928,0.0,101.060867,2011-07-02,220184
2011-07-02 12:38:38.122972672,0.0,101.012466,2011-07-02,220323
2011-07-02 12:38:38.132990720,0.0,101.126572,2011-07-02,220102
2011-07-02 12:38:38.142968320,0.0,101.234924,2011-07-02,220112
2011-07-02 12:38:38.162964224,0.0,101.432404,2011-07-02,220203
2011-07-02 12:38:38.182960128,0.0,101.610352,2011-07-02,220283
2011-07-02 12:38:38.202956032,0.0,101.772858,2011-07-02,230184
2011-07-02 12:38:38.222992128,0.0,101.919014,2011-07-02,222403
2011-07-02 12:38:38.242988032,0.0,102.056885,2011-07-02,231083
2011-07-02 12:38:38.262983936,0.0,102.182800,2011-07-02,231083
2011-07-02 12:38:38.282979840,0.0,102.300697,2011-07-02,231003
2011-07-02 12:38:38.302975488,0.0,102.411003,2011-07-02,231085
2011-07-02 12:38:38.322971392,0.0,102.514168,2011-07-02,231085
2011-07-02 12:38:38.342967296,0.0,102.611870,2011-07-02,230321
2011-07-02 12:38:38.362963200,0.0,102.704681,2011-07-02,230321
2011-07-02 12:38:38.382959104,0.0,102.791969,2011-07-02,230382
2011-07-02 12:38:38.402955008,0.0,102.875404,2011-07-02,230382
2011-07-02 12:38:38.422991104,0.0,102.955002,2011-07-02,230382
2011-07-02 12:38:38.442987008,0.0,103.031143,2011-07-02,230382
2011-07-02 12:38:38.462982656,0.0,103.104843,2011-07-02,230381
2011-07-02 12:38:38.482978560,0.0,103.173973,2011-07-02,230381
2011-07-02 12:38:42.772957440,0.0,103.020065,2011-07-02,230381
2011-07-02 12:38:42.792953344,0.0,102.951492,2011-07-02,230381
2011-07-02 12:38:42.812949248,0.0,102.879807,2011-07-02,230381
2011-07-02 12:38:42.832944896,0.0,102.805656,2011-07-02,230381
2011-07-02 12:38:42.852940800,0.0,102.728821,2011-07-02,230382
2011-07-02 12:38:42.872976896,0.0,102.648315,2011-07-02,230382
2011-07-02 12:38:42.892972800,0.0,102.564125,2011-07-02,230382
2011-07-02 12:38:42.912968704,0.0,102.475845,2011-07-02,230382
2011-07-02 12:38:42.932964608,0.0,102.383133,2011-07-02,230306
2011-07-02 12:38:42.952960512,0.0,102.285576,2011-07-02,230304
2011-07-02 12:38:42.972956416,0.0,102.182602,2011-07-02,231025
2011-07-02 12:38:42.992952064,0.0,102.071609,2011-07-02,231083
2011-07-02 12:38:43.012947968,0.0,101.955536,2011-07-02,231083
2011-07-02 12:38:43.032943872,0.0,101.828911,2011-07-02,230183
2011-07-02 12:38:43.052939776,0.0,101.695236,2011-07-02,230183
2011-07-02 12:38:43.072975872,0.0,101.548637,2011-07-02,230184
2011-07-02 12:38:43.092971776,0.0,101.389175,2011-07-02,220283
2011-07-02 12:38:43.112967680,0.0,101.215950,2011-07-02,220283
2011-07-02 12:38:43.132963584,0.0,101.024666,2011-07-02,220113
2011-07-02 12:38:43.142941184,0.0,100.920563,2011-07-02,220103
2011-07-02 12:38:43.152959232,0.0,100.809402,2011-07-02,220184
2011-07-02 12:38:43.162977280,0.0,100.692245,2011-07-02,220184
2011-07-02 12:38:44.722977024,0.0,100.643257,2011-07-02,220184
2011-07-02 12:38:44.732954880,0.0,100.757767,2011-07-02,220106
2011-07-02 12:38:44.742972928,0.0,100.864754,2011-07-02,220113
2011-07-02 12:38:44.752950784,0.0,100.965752,2011-07-02,220113
2011-07-02 12:38:44.772946432,0.0,101.153015,2011-07-02,220283
2011-07-02 12:38:44.792942336,0.0,101.321739,2011-07-02,220283
2011-07-02 12:38:44.812938240,0.0,101.475182,2011-07-02,230184
2011-07-02 12:38:44.832974336,0.0,101.615494,2011-07-02,230183
2011-07-02 12:38:44.852970240,0.0,101.747559,2011-07-02,230183
2011-07-02 12:38:44.872966144,0.0,101.868660,2011-07-02,231083
2011-07-02 12:38:44.892962048,0.0,101.982239,2011-07-02,231083
2011-07-02 12:38:44.912957952,0.0,102.088722,2011-07-02,231025
2011-07-02 12:38:44.932953600,0.0,102.188515,2011-07-02,230304
2011-07-02 12:38:44.952949504,0.0,102.283592,2011-07-02,230321
2011-07-02 12:38:44.972945408,0.0,102.373268,2011-07-02,230382
2011-07-02 12:38:44.992941312,0.0,102.458580,2011-07-02,230382
2011-07-02 12:38:45.012977408,0.0,102.539337,2011-07-02,230382
2011-07-02 12:38:45.032973312,0.0,102.617348,2011-07-02,230381
2011-07-02 12:38:45.052969216,0.0,102.691238,2011-07-02,230381
2011-07-02 12:38:45.072965120,0.0,102.762939,2011-07-02,230381
2011-07-02 12:38:45.092960768,0.0,102.830872,2011-07-02,230381
2011-07-02 12:38:45.112956672,0.0,102.897644,2011-07-02,230381
2011-07-02 12:38:49.342947840,0.0,102.741493,2011-07-02,230381
2011-07-02 12:38:49.362943744,0.0,102.676155,2011-07-02,230381
2011-07-02 12:38:49.382939648,0.0,102.608627,2011-07-02,230381
2011-07-02 12:38:49.402935552,0.0,102.539009,2011-07-02,230381
2011-07-02 12:38:49.422931456,0.0,102.466164,2011-07-02,230381
2011-07-02 12:38:49.442927360,0.0,102.391075,2011-07-02,230523
2011-07-02 12:38:49.462923008,0.0,102.312927,2011-07-02,230523
2011-07-02 12:38:49.482918912,0.0,102.230431,2011-07-02,230904
2011-07-02 12:38:49.502955008,0.0,102.144974,2011-07-02,230902
2011-07-02 12:38:49.522950912,0.0,102.053879,2011-07-02,230902
2011-07-02 12:38:49.542946816,0.0,101.959816,2011-07-02,230921
2011-07-02 12:38:49.562942720,0.0,101.859398,2011-07-02,231025
2011-07-02 12:38:49.582938624,0.0,101.752625,2011-07-02,231025
2011-07-02 12:38:49.602934528,0.0,101.639519,2011-07-02,231083
2011-07-02 12:38:49.622930176,0.0,101.518723,2011-07-02,230183
2011-07-02 12:38:49.642926080,0.0,101.389694,2011-07-02,230183
2011-07-02 12:38:49.662921984,0.0,101.250610,2011-07-02,230183
2011-07-02 12:38:49.682917888,0.0,101.098480,2011-07-02,230184
2011-07-02 12:38:49.702953984,0.0,100.932343,2011-07-02,220182
2011-07-02 12:38:49.722949888,0.0,100.752014,2011-07-02,220183
2011-07-02 12:38:49.742945792,0.0,100.549316,2011-07-02,220122
2011-07-02 12:38:49.752923648,0.0,100.439507,2011-07-02,220122
2011-07-02 12:38:49.762941696,0.0,100.323792,2011-07-02,220722
2011-07-02 12:38:51.322941184,0.0,100.273804,2011-07-02,220722
2011-07-02 12:38:51.332919040,0.0,100.386917,2011-07-02,220122
2011-07-02 12:38:51.342937088,0.0,100.495224,2011-07-02,220122
2011-07-02 12:38:51.362932992,0.0,100.689354,2011-07-02,220183
2011-07-02 12:38:51.382928896,0.0,100.867455,2011-07-02,220182
2011-07-02 12:38:51.402924544,0.0,101.027168,2011-07-02,230184
2011-07-02 12:38:51.422920448,0.0,101.172935,2011-07-02,230183
2011-07-02 12:38:51.442956544,0.0,101.309120,2011-07-02,230129
2011-07-02 12:38:51.462952448,0.0,101.434784,2011-07-02,230183
2011-07-02 12:38:51.482948352,0.0,101.551857,2011-07-02,231083
2011-07-02 12:38:51.502944256,0.0,101.661400,2011-07-02,231025
2011-07-02 12:38:51.522940160,0.0,101.763870,2011-07-02,230921
2011-07-02 12:38:51.542936064,0.0,101.860924,2011-07-02,230921
2011-07-02 12:38:51.562931712,0.0,101.953636,2011-07-02,230902
2011-07-02 12:38:51.582927616,0.0,102.039879,2011-07-02,230902
2011-07-02 12:38:51.602923520,0.0,102.123253,2011-07-02,230523
2011-07-02 12:38:51.622919424,0.0,102.201927,2011-07-02,230523
2011-07-02 12:38:51.642955520,0.0,102.278023,2011-07-02,230523
2011-07-02 12:38:51.662951424,0.0,102.350502,2011-07-02,230523
2011-07-02 12:38:51.682947328,0.0,102.419998,2011-07-02,230523
2011-07-02 12:38:51.702943232,0.0,102.486801,2011-07-02,230381
2011-07-02 12:38:51.722939136,0.0,102.551895,2011-07-02,230381
2011-07-02 12:38:51.742934784,0.0,102.614548,2011-07-02,230381
2011-07-02 12:38:55.932934400,0.0,102.395515,2011-07-02,230524
2011-07-02 12:38:55.952930048,0.0,102.331360,2011-07-02,230524
2011-07-02 12:38:55.972925952,0.0,102.265121,2011-07-02,230523
2011-07-02 12:38:55.992921856,0.0,102.197273,2011-07-02,230523
2011-07-02 12:38:56.012917760,0.0,102.125603,2011-07-02,230523
2011-07-02 12:38:56.032913664,0.0,102.052261,2011-07-02,230523
2011-07-02 12:38:56.052909568,0.0,101.975441,2011-07-02,230523
2011-07-02 12:38:56.072905472,0.0,101.895836,2011-07-02,230523
2011-07-02 12:38:56.092901120,0.0,101.811691,2011-07-02,230523
2011-07-02 12:38:56.112937216,0.0,101.723938,2011-07-02,230822
2011-07-02 12:38:56.132933120,0.0,101.631271,2011-07-02,230822
2011-07-02 12:38:56.152929024,0.0,101.534836,2011-07-02,230921
2011-07-02 12:38:56.172924928,0.0,101.431496,2011-07-02,231025
2011-07-02 12:38:56.192920832,0.0,101.322250,2011-07-02,230124
2011-07-02 12:38:56.212916736,0.0,101.206337,2011-07-02,230124
2011-07-02 12:38:56.232912640,0.0,101.081207,2011-07-02,230129
2011-07-02 12:38:56.252908288,0.0,100.948494,2011-07-02,230183
2011-07-02 12:38:56.272904192,0.0,100.802963,2011-07-02,230112
2011-07-02 12:38:56.292940288,0.0,100.645470,2011-07-02,230184
2011-07-02 12:38:56.312936192,0.0,100.472824,2011-07-02,220781
2011-07-02 12:38:56.332932096,0.0,100.283943,2011-07-02,220122
2011-07-02 12:38:56.342909952,0.0,100.178955,2011-07-02,220122
2011-07-02 12:38:56.352928000,0.0,100.069611,2011-07-02,220122
2011-07-02 12:38:56.362905856,0.0,99.953461,2011-07-02,220721
2011-07-02 12:38:57.922905344,0.0,99.905342,2011-07-02,220721
2011-07-02 12:38:57.932923392,0.0,100.017029,2011-07-02,220721
2011-07-02 12:38:57.942901248,0.0,100.123985,2011-07-02,220721
2011-07-02 12:38:57.952919296,0.0,100.224129,2011-07-02,220781
2011-07-02 12:38:57.972915200,0.0,100.409050,2011-07-02,220781
2011-07-02 12:38:57.992911104,0.0,100.577217,2011-07-02,230184
2011-07-02 12:38:58.012907008,0.0,100.729469,2011-07-02,230112
2011-07-02 12:38:58.032902656,0.0,100.868706,2011-07-02,230125
2011-07-02 12:38:58.052938752,0.0,101.000450,2011-07-02,230124
2011-07-02 12:38:58.072934656,0.0,101.120033,2011-07-02,230124
2011-07-02 12:38:58.092930560,0.0,101.233406,2011-07-02,230124
2011-07-02 12:38:58.112926464,0.0,101.338577,2011-07-02,230123
2011-07-02 12:38:58.132922368,0.0,101.438240,2011-07-02,230822
2011-07-02 12:38:58.152918272,0.0,101.532562,2011-07-02,230822
2011-07-02 12:38:58.172914176,0.0,101.621269,2011-07-02,230822
2011-07-02 12:38:58.192910080,0.0,101.705589,2011-07-02,230503
2011-07-02 12:38:58.212905728,0.0,101.786316,2011-07-02,230523
2011-07-02 12:38:58.232901632,0.0,101.863449,2011-07-02,230523
2011-07-02 12:38:58.252937728,0.0,101.937325,2011-07-02,230523
2011-07-02 12:38:58.272933632,0.0,102.008247,2011-07-02,230523
2011-07-02 12:38:58.292929536,0.0,102.076180,2011-07-02,230523
2011-07-02 12:38:58.312925440,0.0,102.142586,2011-07-02,230523
2011-07-02 12:38:58.332921344,0.0,102.205772,2011-07-02,230524
2011-07-02 12:38:58.352917248,0.0,102.267563,2011-07-02,230524
2011-07-02 12:38:58.372912896,0.0,102.326851,2011-07-02,230524
2011-07-02 12:39:02.502884608,0.0,102.110069,2011-07-02,230524
2011-07-02 12:39:02.522920704,0.0,102.048904,2011-07-02,230524
2011-07-02 12:39:02.542916608,0.0,101.985840,2011-07-02,230524
2011-07-02 12:39:02.562912512,0.0,101.921165,2011-07-02,230882
2011-07-02 12:39:02.582908160,0.0,101.853653,2011-07-02,230882
2011-07-02 12:39:02.602904064,0.0,101.784401,2011-07-02,230882
2011-07-02 12:39:02.622899968,0.0,101.711945,2011-07-02,230882
2011-07-02 12:39:02.642895872,0.0,101.637268,2011-07-02,230522
2011-07-02 12:39:02.662891776,0.0,101.559135,2011-07-02,230522
2011-07-02 12:39:02.682887680,0.0,101.477539,2011-07-02,230505
2011-07-02 12:39:02.702883584,0.0,101.392113,2011-07-02,230521
2011-07-02 12:39:02.722919680,0.0,101.302048,2011-07-02,230826
2011-07-02 12:39:02.742915328,0.0,101.208572,2011-07-02,230822
2011-07-02 12:39:02.762911232,0.0,101.108795,2011-07-02,230123
2011-07-02 12:39:02.782907136,0.0,101.003296,2011-07-02,230128
2011-07-02 12:39:02.802903040,0.0,100.890373,2011-07-02,230128
2011-07-02 12:39:02.822898944,0.0,100.771049,2011-07-02,230128
2011-07-02 12:39:02.842894848,0.0,100.642296,2011-07-02,230127
2011-07-02 12:39:02.862890752,0.0,100.504936,2011-07-02,230125
2011-07-02 12:39:02.882886656,0.0,100.353226,2011-07-02,230112
2011-07-02 12:39:02.902882304,0.0,100.188377,2011-07-02,230113

In [77]:
test = df_temp[df_temp['region']=="232721"]
test = test[test['date']=="2012-01-01"]
pd.set_option('display.max_rows', 500)
test.head(200)

Empty DataFrame
Columns: [CERES_SW_TOA_flux___upwards, CERES_viewing_zenith_at_surface, date, region]
Index: []

In [78]:
test2 = df_temp[df_temp['region']=="232721"]
test2 = test2[test2['date']=="2012-01-02"]
pd.set_option('display.max_rows', 500)
test2.head(500)

Empty DataFrame
Columns: [CERES_SW_TOA_flux___upwards, CERES_viewing_zenith_at_surface, date, region]
Index: []

In [79]:
test2 = df_temp[df_temp['region']=="310114"]
test2 = test2[test2['date']=="2012-02-05"]
pd.set_option('display.max_rows', 500)
test2.head(500)

Empty DataFrame
Columns: [CERES_SW_TOA_flux___upwards, CERES_viewing_zenith_at_surface, date, region]
Index: []

In [ ]:
import xarray as xr
with xr.open_dataset("/Users/anora/Desktop/MCD06COSP_D3_MODIS.A2016001.062.2022124091724.nc") as ds:
    ds
ds

<xarray.Dataset>
Dimensions:    (latitude: 180, longitude: 360)
Coordinates:
  * latitude   (latitude) float64 -89.5 -88.5 -87.5 -86.5 ... 87.5 88.5 89.5
  * longitude  (longitude) float64 -179.5 -178.5 -177.5 ... 177.5 178.5 179.5
Data variables:
    *empty*
Attributes: (12/51)
    YAML_config:                       grid_settings:\n  gridsize: 1\n  proje...
    Yori_version:                      1.5.0
    input_files:                       MCD06COSP_G3_MODIS_Aqua.A2016001.0000....
    daily_defn_of_day_adjustment:      False
    history:
    source:                            idl 8.4, mcd06cosp_preyori 20220218-1,...
    ...                                ...
    longitude_resolution:              1.0
    license:                           http://science.nasa.gov/earth-science/...
    stdname_vocabulary:                NetCDF Climate and Forecast (CF) Metad...
    keywords_vocabulary:               NASA Global Change Master Directory (G...
    keywords:                          EARTH SCIENCE > ATMOSPHERE > CLOUDS > ...
    naming_authority:                  gov.nasa.gsfc.sci.atmos

In [6]:
import netCDF4 as nc
ncf = nc.Dataset("/Users/anora/Desktop/MCD06COSP_D3_MODIS.A2016001.062.2022124091724.nc")

for group_name in ncf.groups:
    group = ncf.groups[group_name]

thickness_data = ncf.groups["Cloud_Optical_Thickness_Total"] 

fraction_data= ncf.groups['Cloud_Mask_Fraction']
fraction_data

<class 'netCDF4.Group'>
group /Cloud_Mask_Fraction:
    long_name: Cloud Fraction from Cloud Mask for Daytime Scenes
    units: none
    _FillValue: -999.0
    valid_min: 0.0
    valid_max: 1.0
    scale_factor: 1.0
    add_offset: 0.0
    dimensions(sizes):
    variables(dimensions): float64 Mean(longitude, latitude), float64 Standard_Deviation(longitude, latitude), float64 Sum(longitude, latitude), int32 Pixel_Counts(longitude, latitude), float64 Sum_Squares(longitude, latitude)
    groups: